spring.application.name=cabservice
spring.datasource.username=root
spring.datasource.password=Aman@7992
spring.datasource.url=jdbc:mysql://localhost:3306/cabservice_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true